name: unimedvl
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.18
  - pip=25.1
  - pip:
      - torch==2.5.1
      - torchvision==0.20.1
      - triton==3.1.0
      - transformers==4.49.0
      - accelerate==1.7.0
      - safetensors==0.4.5
      - tokenizers==0.21.1
      - sentencepiece==0.1.99
      - pillow==11.2.1
      - numpy==1.24.4
      - opencv-python==4.7.0.72
      - einops==0.8.1
      - matplotlib==3.7.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.58.2
      - kiwisolver==1.4.8
      - packaging==25.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0post0
      - ipykernel==6.29.5
      - jupyter_client==8.6.3
      - flash-attn # should be added manually compatible to your torch and python versions
